import React from 'react'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Header from '@/components/header'
import Body from '../components/about/Body'

export default function about() {
  return (
    <>

        <Head>
        <title>About Articulate: Music and Lyrics</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main className={styles.main}>
        <Header/>
        <Body/>
        </main>
    </>
  )
}
